apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secret
  namespace: database
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/gke-new-2026/secrets/postgres-password/versions/latest"
        fileName: "dbpassword"
